codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "80..100"

  status:
    project:
      default:
        target: 95%
        threshold: 2%
        base: auto
        paths:
          - "src/"
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
