[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cobra-lenguaje"
version = "10.0.7a0"
description = "Un lenguaje de programación en español para simulaciones y más."
authors = [ {name = "Adolfo González Hernández", email = "adolfogonzal@gmail.com"} ]
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
keywords = ["cobra", "lenguaje", "cli"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "numpy>=1.19.3",
    "scipy>=1.5.4",
    "matplotlib>=3.2.2",
    "pandas>=1.1.3",
    "tensorflow>=2.5.0",
    "dask>=0.19.0",
    "DEAP>=1.3.1",
    "agix>=0.2.0",
    "holobit-sdk>=1.0.0; python_version >= '3.10'",
    "smooth-criminal>=0.1.0",
    "tomli>=0.2.0",
    "PyYAML>=5.3.1",
    "jsonschema>=4.0.1",
    "python-dotenv>=0.19.0",
    "pexpect>=4.9.0",
    "requests>=2.19.0",
    "flet>=0.1.0",
    "packaging>=17.0",
    "pybind11>=2.6.0",
    "RestrictedPython>=5.1",
    "prompt_toolkit>=3.0.0",
    "Pygments>=2.4.0",
]

[project.urls]
Documentation = "https://github.com/Alphonsus411/pCobra#readme"
Source = "https://github.com/Alphonsus411/pCobra"

[project.optional-dependencies]
mutation = ["mutpy>=0.6.1"]
notebooks = [
    "papermill>=2.6.0",
    "nbconvert>=7.16.6",
    "ipykernel>=6.29.5",
]
dev = [
    "python-dotenv",
    "python-lsp-server",
    "hypothesis",
    "ipykernel>=6.29.5",
    "tree-sitter-languages>=1.10.2",
    "pytest",
    "pytest-cov",
    "pytest-timeout",
    "ruff",
    "mypy",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
cobra = "cobra.cli.cli:main"
pcobra = "src.main:main"

[project.entry-points."cobra.plugins"]
# Se registrarán plugins externos aquí

[project.entry-points."cobra.transpilers"]
# Se registrarán transpiladores externos aquí

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["backend", "src"]
