[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cobra-lenguaje"
version = "8.0.0"
description = "Un lenguaje de programación en español para simulaciones y más."
authors = [ {name = "Adolfo González Hernández", email = "adolfogonzal@gmail.com"} ]
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
keywords = ["cobra", "lenguaje", "cli"]

dependencies = [
    "pytest>=7.0",
    "hypothesis>=6.0",
    "numpy>=1.22.0",
    "scipy>=1.7.0",
    "matplotlib>=3.5.0",
    "pandas>=1.3.0",
    "tensorflow>=2.6.0",
    "dask>=2021.09.0",
    "DEAP>=1.3.1",
    "ipykernel>=6.0.0",
    "agix==0.8.3",
    "holobit-sdk",
    "smooth-criminal",
    "tomli",
]

[project.urls]
Documentation = "https://github.com/Alphonsus411/pCobra#readme"
Source = "https://github.com/Alphonsus411/pCobra"

[project.optional-dependencies]
mutation = ["mutpy>=0.6.1"]
notebooks = [
    "papermill>=2.6.0",
    "nbconvert>=7.16.6",
]

[tool.setuptools]
package-dir = {"" = "backend/src"}

[tool.setuptools.packages.find]
where = ["backend/src"]

[project.scripts]
cobra = "src.cli.cli:main"

[project.entry-points."cobra.plugins"]
# Se registrarán plugins externos aquí

[project.entry-points."cobra.transpilers"]
# Se registrarán transpiladores externos aquí
