"""Módulos de arquitectura interna de pCobra."""

from pcobra.cobra.architecture.capabilities_contract import (
    PROJECT_TYPE_PUBLIC_POLICY,
    PUBLIC_CAPABILITIES_CONTRACT,
    PUBLIC_FALLBACK_POLICY,
)
from pcobra.cobra.architecture.unified_ecosystem import (
    BINDING_BLUEPRINTS,
    IMPORT_POLICY_BLUEPRINT,
    LEGACY_BACKEND_REMOVAL_CANDIDATES,
    OFFICIAL_EXECUTION_BACKENDS,
    OFFICIAL_USER_LANGUAGE,
    STDLIB_BLUEPRINTS,
    build_refactor_workplan,
)
from pcobra.cobra.architecture.overview import (
    INTERNAL_MIGRATION_ONLY_SURFACES,
    PUBLIC_ARCHITECTURE_OVERVIEW,
    PUBLIC_CLI_V2_COMMANDS,
    PUBLIC_FLOW_DIAGRAM,
    PUBLIC_LANGUAGE_BOUNDARY,
    USER_ROUTE_BACKEND_ENTRYPOINT,
)

__all__ = [
    "PROJECT_TYPE_PUBLIC_POLICY",
    "PUBLIC_CAPABILITIES_CONTRACT",
    "PUBLIC_FALLBACK_POLICY",
    "OFFICIAL_USER_LANGUAGE",
    "OFFICIAL_EXECUTION_BACKENDS",
    "LEGACY_BACKEND_REMOVAL_CANDIDATES",
    "STDLIB_BLUEPRINTS",
    "IMPORT_POLICY_BLUEPRINT",
    "BINDING_BLUEPRINTS",
    "build_refactor_workplan",
    "PUBLIC_LANGUAGE_BOUNDARY",
    "PUBLIC_CLI_V2_COMMANDS",
    "USER_ROUTE_BACKEND_ENTRYPOINT",
    "INTERNAL_MIGRATION_ONLY_SURFACES",
    "PUBLIC_ARCHITECTURE_OVERVIEW",
    "PUBLIC_FLOW_DIAGRAM",
]
