from __future__ import annotations


def build_standard_runtime_lines() -> list[str]:
    return [
        "use crate::corelibs::*;",
        "use crate::standard_library::*;",
        "use std::fmt::Display;",
        "",
        "fn longitud<T: ToString>(valor: T) -> usize {",
        "    valor.to_string().chars().count()",
        "}",
        "",
        "fn mostrar<T: Display>(valor: T) {",
        "    println!(\"{}\", valor);",
        "}",
    ]



def build_holobit_runtime_lines() -> list[str]:
    return [
        "const COBRA_HOLOBIT_PARTIAL_CONTRACT_NOTE: &str = \"contrato partial: adaptador oficial mantenido por el proyecto; no equivale a holobit_sdk ni a la semántica completa de Python\";",
        "",
        "fn cobra_holobit_partial_contract_error(feature: &str, detail: impl Into<String>) -> CobraRuntimeError {",
        "    CobraRuntimeError::new(format!(\"Runtime Holobit Rust: feature={}; contrato partial; backend sin holobit_sdk; {}. {}\", feature, detail.into(), COBRA_HOLOBIT_PARTIAL_CONTRACT_NOTE))",
        "}",
        "",
        "fn cobra_param_as_f64(feature: &str, value: &str) -> Result<f64, CobraRuntimeError> {",
        "    value.trim().parse::<f64>().map_err(|_| {",
        "        cobra_holobit_partial_contract_error(",
        "            feature,",
        "            format!(\"parámetro numérico no soportado por el adaptador oficial: {}\", value),",
        "        )",
        "    })",
        "}",
        "",
        "fn cobra_runtime_expect<T>(result: Result<T, CobraRuntimeError>) -> T {",
        "    match result {",
        "        Ok(value) => value,",
        "        Err(error) => panic!(\"{}\", error),",
        "    }",
        "}",
        "",
        "#[derive(Clone, Debug, PartialEq)]",
        "struct CobraHolobit {",
        "    valores: Vec<f64>,",
        "    historial: Vec<String>,",
        "}",
        "",
        "#[derive(Clone, Debug, PartialEq)]",
        "struct CobraRuntimeError {",
        "    mensaje: String,",
        "}",
        "",
        "impl CobraRuntimeError {",
        "    fn new(mensaje: impl Into<String>) -> Self {",
        "        Self { mensaje: mensaje.into() }",
        "    }",
        "}",
        "",
        "impl std::fmt::Display for CobraRuntimeError {",
        "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
        "        write!(f, \"{}\", self.mensaje)",
        "    }",
        "}",
        "",
        "impl std::error::Error for CobraRuntimeError {}",
        "",
        "fn cobra_holobit(valores: Vec<f64>) -> CobraHolobit {",
        "    CobraHolobit {",
        "        valores,",
        "        historial: vec![\"creado\".to_string()],",
        "    }",
        "}",
        "",
        "fn cobra_proyectar(hb: &CobraHolobit, modo: &str) -> Result<Vec<f64>, CobraRuntimeError> {",
        "    match modo.to_ascii_lowercase().as_str() {",
        "        \"1d\" | \"linea\" => Ok(hb.valores.iter().cloned().take(1).collect()),",
        "        \"2d\" | \"plano\" => {",
        "            let mut salida = hb.valores.iter().cloned().take(2).collect::<Vec<_>>();",
        "            while salida.len() < 2 {",
        "                salida.push(0.0);",
        "            }",
        "            Ok(salida)",
        "        }",
        "        \"3d\" | \"espacio\" => {",
        "            let mut salida = hb.valores.iter().cloned().take(3).collect::<Vec<_>>();",
        "            while salida.len() < 3 {",
        "                salida.push(0.0);",
        "            }",
        "            Ok(salida)",
        "        }",
        "        \"vector\" => Ok(hb.valores.clone()),",
        "        _ => Err(cobra_holobit_partial_contract_error(",
        "            \"proyectar\",",
        "            format!(\"modo de proyección no soportado por el adaptador oficial: {}\", modo),",
        "        )),",
        "    }",
        "}",
        "",
        "fn cobra_transformar(",
        "    hb: &CobraHolobit,",
        "    op: &str,",
        "    params: &[String],",
        ") -> Result<CobraHolobit, CobraRuntimeError> {",
        "    let operacion = op.to_ascii_lowercase();",
        "    let mut valores = hb.valores.clone();",
        "",
        "    match operacion.as_str() {",
        "        \"escalar\" => {",
        "            let factor = match params.first() {",
        "                Some(value) => cobra_param_as_f64(\"transformar\", value)?,",
        "                None => 1.0,",
        "            };",
        "            valores = valores.into_iter().map(|valor| valor * factor).collect();",
        "        }",
        "        \"normalizar\" => {",
        "            let maximo = valores",
        "                .iter()",
        "                .fold(1.0_f64, |acc, valor| acc.max(valor.abs()));",
        "            valores = valores.into_iter().map(|valor| valor / maximo).collect();",
        "        }",
        "        \"mover\" | \"trasladar\" => {",
        "            while valores.len() < 3 {",
        "                valores.push(0.0);",
        "            }",
        "            valores[0] += match params.get(0) {",
        "                Some(value) => cobra_param_as_f64(\"transformar\", value)?,",
        "                None => 0.0,",
        "            };",
        "            valores[1] += match params.get(1) {",
        "                Some(value) => cobra_param_as_f64(\"transformar\", value)?,",
        "                None => 0.0,",
        "            };",
        "            valores[2] += match params.get(2) {",
        "                Some(value) => cobra_param_as_f64(\"transformar\", value)?,",
        "                None => 0.0,",
        "            };",
        "        }",
        "        \"rotar\" => {",
        "            while valores.len() < 3 {",
        "                valores.push(0.0);",
        "            }",
        "            let (eje, grados_index) = match params.first() {",
        "                Some(candidate) if !candidate.trim().is_empty() => {",
        "                    let normalizado = candidate.trim().to_ascii_lowercase();",
        "                    if normalizado == \"x\" || normalizado == \"y\" || normalizado == \"z\" {",
        "                        (normalizado, 1usize)",
        "                    } else {",
        "                        (\"z\".to_string(), 0usize)",
        "                    }",
        "                }",
        "                _ => (\"z\".to_string(), 0usize),",
        "            };",
        "            if eje != \"z\" {",
        "                return Err(cobra_holobit_partial_contract_error(",
        "                    \"transformar\",",
        "                    format!(\"rotación soportada solo sobre eje z en el adaptador oficial, recibido {}\", eje),",
        "                ));",
        "            }",
        "            let grados = match params.get(grados_index) {",
        "                Some(value) => cobra_param_as_f64(\"transformar\", value)?,",
        "                None => 0.0,",
        "            };",
        "            let radianes = grados.to_radians();",
        "            let (x, y, z) = (valores[0], valores[1], valores[2]);",
        "            valores = vec![",
        "                (x * radianes.cos() - y * radianes.sin()),",
        "                (x * radianes.sin() + y * radianes.cos()),",
        "                z,",
        "            ];",
        "        }",
        "        _ => {",
        "            return Err(cobra_holobit_partial_contract_error(",
        "                \"transformar\",",
        "                format!(\"operación no soportada por el adaptador oficial: {}\", op),",
        "            ));",
        "        }",
        "    }",
        "",
        "    Ok(CobraHolobit {",
        "        valores,",
        "        historial: {",
        "            let mut historial = hb.historial.clone();",
        "            historial.push(format!(\"transformar:{}\", operacion));",
        "            historial",
        "        },",
        "    })",
        "}",
        "",
        "fn cobra_graficar(hb: &CobraHolobit) -> Result<String, CobraRuntimeError> {",
        "    let vista = format!(\"Holobit({:?})\", hb.valores);",
        "    mostrar(vista.clone());",
        "    Ok(vista)",
        "}",
    ]
