def build_holobit_runtime_lines() -> list[str]:
    return [
        'type CobraHolobit struct {',
        '    Valores []float64',
        '    Historial []string',
        '}',
        '',
        'func cobra_holobit(valores []float64) CobraHolobit {',
        '    copia := append([]float64(nil), valores...)',
        '    return CobraHolobit{Valores: copia, Historial: []string{"creado"}}',
        '}',
        '',
        'func cobra_normalizar_holobit(valor any) CobraHolobit {',
        '    switch hb := valor.(type) {',
        '    case CobraHolobit:',
        '        copiaValores := append([]float64(nil), hb.Valores...)',
        '        copiaHistorial := append([]string(nil), hb.Historial...)',
        '        return CobraHolobit{Valores: copiaValores, Historial: copiaHistorial}',
        '    case []float64:',
        '        return cobra_holobit(hb)',
        '    case []int:',
        '        valores := make([]float64, len(hb))',
        '        for i, item := range hb {',
        '            valores[i] = float64(item)',
        '        }',
        '        return cobra_holobit(valores)',
        '    default:',
        '        panic(fmt.Sprintf("Runtime Holobit Go: valor no compatible para holobit: %v", valor))',
        '    }',
        '}',
        '',
        'func cobra_dimensionar(valores []float64, dimension int) []float64 {',
        '    salida := append([]float64(nil), valores...)',
        '    if len(salida) > dimension {',
        '        salida = salida[:dimension]',
        '    }',
        '    for len(salida) < dimension {',
        '        salida = append(salida, 0)',
        '    }',
        '    return salida',
        '}',
        '',
        'func cobra_to_float(valor any) float64 {',
        '    switch v := valor.(type) {',
        '    case int:',
        '        return float64(v)',
        '    case int32:',
        '        return float64(v)',
        '    case int64:',
        '        return float64(v)',
        '    case float32:',
        '        return float64(v)',
        '    case float64:',
        '        return v',
        '    case string:',
        '        parsed, err := strconv.ParseFloat(v, 64)',
        '        if err == nil {',
        '            return parsed',
        '        }',
        '    }',
        '    panic(fmt.Sprintf("Runtime Holobit Go: parámetro numérico no compatible: %v", valor))',
        '}',
        '',
        'func cobra_proyectar(hb any, modo any) []float64 {',
        '    holobit := cobra_normalizar_holobit(hb)',
        '    switch strings.ToLower(strings.TrimSpace(fmt.Sprint(modo))) {',
        '    case "1d", "linea":',
        '        return cobra_dimensionar(holobit.Valores, 1)',
        '    case "2d", "plano":',
        '        return cobra_dimensionar(holobit.Valores, 2)',
        '    case "3d", "espacio":',
        '        return cobra_dimensionar(holobit.Valores, 3)',
        '    case "vector":',
        '        return append([]float64(nil), holobit.Valores...)',
        '    default:',
        '        panic(fmt.Sprintf("Runtime Holobit Go: modo de proyección no soportado por el adaptador oficial: %v", modo))',
        '    }',
        '}',
        '',
        'func cobra_transformar(hb any, op any, params ...any) CobraHolobit {',
        '    holobit := cobra_normalizar_holobit(hb)',
        '    operacion := strings.ToLower(strings.TrimSpace(fmt.Sprint(op)))',
        '    valores := append([]float64(nil), holobit.Valores...)',
        '    switch operacion {',
        '    case "escalar":',
        '        factor := 1.0',
        '        if len(params) > 0 {',
        '            factor = cobra_to_float(params[0])',
        '        }',
        '        for i := range valores {',
        '            valores[i] *= factor',
        '        }',
        '    case "normalizar":',
        '        maximo := 1.0',
        '        for _, valor := range valores {',
        '            abs := math.Abs(valor)',
        '            if abs > maximo {',
        '                maximo = abs',
        '            }',
        '        }',
        '        for i := range valores {',
        '            valores[i] /= maximo',
        '        }',
        '    case "mover", "trasladar":',
        '        valores = cobra_dimensionar(valores, 3)',
        '        if len(params) > 0 {',
        '            valores[0] += cobra_to_float(params[0])',
        '        }',
        '        if len(params) > 1 {',
        '            valores[1] += cobra_to_float(params[1])',
        '        }',
        '        if len(params) > 2 {',
        '            valores[2] += cobra_to_float(params[2])',
        '        }',
        '    case "rotar":',
        '        valores = cobra_dimensionar(valores, 3)',
        '        eje := "z"',
        '        gradosIndex := 0',
        '        if len(params) > 0 {',
        '            if texto, ok := params[0].(string); ok {',
        '                eje = strings.ToLower(strings.TrimSpace(texto))',
        '                gradosIndex = 1',
        '            }',
        '        }',
        '        if eje != "z" {',
        '            panic(fmt.Sprintf("Runtime Holobit Go: rotación soportada solo sobre eje z en el adaptador oficial, recibido %s", eje))',
        '        }',
        '        grados := 0.0',
        '        if len(params) > gradosIndex {',
        '            grados = cobra_to_float(params[gradosIndex])',
        '        }',
        '        radianes := grados * math.Pi / 180.0',
        '        x := valores[0]',
        '        y := valores[1]',
        '        valores[0] = math.Round((x*math.Cos(radianes)-y*math.Sin(radianes))*1e6) / 1e6',
        '        valores[1] = math.Round((x*math.Sin(radianes)+y*math.Cos(radianes))*1e6) / 1e6',
        '    default:',
        '        panic(fmt.Sprintf("Runtime Holobit Go: operación no soportada por el adaptador oficial: %v", op))',
        '    }',
        '    historial := append([]string(nil), holobit.Historial...)',
        '    historial = append(historial, fmt.Sprintf("transformar:%s", operacion))',
        '    return CobraHolobit{Valores: valores, Historial: historial}',
        '}',
        '',
        'func longitud(valor any) int {',
        '    switch v := valor.(type) {',
        '    case string:',
        '        return len([]rune(v))',
        '    case []any:',
        '        return len(v)',
        '    case []float64:',
        '        return len(v)',
        '    case []int:',
        '        return len(v)',
        '    case CobraHolobit:',
        '        return len(v.Valores)',
        '    default:',
        '        return len([]rune(fmt.Sprint(valor)))',
        '    }',
        '}',
        '',
        'func mostrar(valores ...any) any {',
        '    fmt.Println(valores...)',
        '    if len(valores) == 0 {',
        '        return nil',
        '    }',
        '    if len(valores) == 1 {',
        '        return valores[0]',
        '    }',
        '    return valores',
        '}',
        '',
        'func cobra_graficar(hb any) string {',
        '    holobit := cobra_normalizar_holobit(hb)',
        '    vista := fmt.Sprintf("Holobit(%v)", holobit.Valores)',
        '    mostrar(vista)',
        '    return vista',
        '}',
    ]
