"""Contrato interno de capacidades canónicas de módulos Cobra."""

from __future__ import annotations

CAPACIDADES_POR_MODULO: dict[str, dict[str, object]] = {
    "numero": {"familia": "numero", "modulo": "pcobra.standard_library.numero", "api_canonica": ('es_finito','es_infinito','es_nan','copiar_signo','signo','limitar','hipotenusa','distancia_euclidiana','raiz_entera','combinaciones','permutaciones','suma_precisa','interpolar','envolver_modular','varianza','varianza_muestral','media_geometrica','media_armonica','percentil','cuartiles','rango_intercuartil','coeficiente_variacion')},
    "texto": {"familia": "texto", "modulo": "pcobra.standard_library.texto", "api_canonica": ('quitar_acentos','normalizar_espacios','es_palindromo','es_anagrama','codificar','decodificar','es_alfabetico','es_alfa_numerico','es_decimal','es_numerico','es_identificador','es_imprimible','es_ascii','es_mayusculas','es_minusculas','es_titulo','es_digito','es_espacio','quitar_prefijo','quitar_sufijo','a_snake','a_camel','quitar_envoltura','prefijo_comun','sufijo_comun','dividir_lineas','dividir_derecha','encontrar','encontrar_derecha','subcadena_antes','subcadena_despues','subcadena_antes_ultima','subcadena_despues_ultima','indice','indice_derecha','contar_subcadena','centrar_texto','rellenar_ceros','minusculas','mayusculas','minusculas_casefold','intercambiar_mayusculas','expandir_tabulaciones','particionar','particionar_derecha','indentar_texto','desindentar_texto','envolver_texto','acortar_texto','formatear','formatear_mapa','tabla_traduccion','traducir')},
    "datos": {"familia": "datos", "modulo": "pcobra.standard_library.datos", "api_canonica": ('leer_csv','leer_json','escribir_csv','escribir_json','leer_excel','escribir_excel','leer_parquet','escribir_parquet','leer_feather','escribir_feather','describir','correlacion_pearson','correlacion_spearman','matriz_covarianza','calcular_percentiles','resumen_rapido','seleccionar_columnas','filtrar','mutar_columna','separar_columna','unir_columnas','agrupar_y_resumir','tabla_cruzada','pivotar_ancho','pivotar_largo','ordenar_tabla','combinar_tablas','rellenar_nulos','desplegar_tabla','pivotar_tabla','agregar','mapear','reducir','claves','valores','longitud')},
    "logica": {"familia": "logica", "modulo": "pcobra.standard_library.logica", "api_canonica": ('es_verdadero','es_falso','conjuncion','disyuncion','negacion','entonces','si_no','coalescer','condicional','xor','nand','nor','implica','equivale','xor_multiple','todas','alguna','ninguna','solo_uno','conteo_verdaderos','paridad','mayoria','exactamente_n','tabla_verdad','diferencia_simetrica')},
    "asincrono": {"familia": "asincrono", "modulo": "pcobra.standard_library.asincrono", "api_canonica": ('grupo_tareas','limitar_tiempo','proteger_tarea','ejecutar_en_hilo','reintentar_async')},
    "sistema": {"familia": "sistema", "modulo": "pcobra.standard_library.sistema", "api_canonica": ('obtener_os','ejecutar','ejecutar_async','ejecutar_stream','obtener_env','listar_dir','directorio_actual')},
    "archivo": {"familia": "archivo", "modulo": "pcobra.standard_library.archivo", "api_canonica": ('leer','escribir','adjuntar','existe')},
    "tiempo": {"familia": "tiempo", "modulo": "pcobra.standard_library.tiempo", "api_canonica": ('ahora','formatear','dormir','epoch','desde_epoch')},
    "red": {"familia": "red", "modulo": "pcobra.standard_library.red", "api_canonica": ('obtener_url','enviar_post','obtener_url_async','enviar_post_async','descargar_archivo','obtener_json')},
    "holobit": {"familia": "holobit", "modulo": "pcobra.standard_library.holobit", "api_canonica": ('crear_holobit','validar_holobit','serializar_holobit','deserializar_holobit','proyectar','transformar','graficar','combinar','medir')},
}

__all__ = ["CAPACIDADES_POR_MODULO"]
