name: Install dependencies
description: Set up Python dependencies
inputs:
  extra:
    description: Extra packages to install
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Upgrade pip and install base dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .
        # pip install -e .[dev] también es válido para extras de desarrollo
        if [ -n "${{ inputs.extra }}" ]; then
          # Split extra packages into an array to avoid shell injection and option parsing
          read -r -a extra_packages <<< "${{ inputs.extra }}"
          pip install -- "${extra_packages[@]}"
        fi

