name: Install dependencies
description: Set up Python dependencies
inputs:
  extra:
    description: Extra packages to install
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Upgrade pip and install base dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        if [ -n "${{ inputs.extra }}" ]; then
          pip install ${{ inputs.extra }}
        fi

