@startuml
Lexer --> Parser
Parser --> AST
AST --> Transpiladores
Transpiladores --> Python
Transpiladores --> JS
Transpiladores --> ASM
Transpiladores --> Rust
Transpiladores --> "C++"
Transpiladores --> Go
Transpiladores --> Java
Transpiladores --> WebAssembly
@enduml
