?start: statement*

?statement: asignacion
          | funcion
          | funcion_asincronica
          | clase
          | enumeracion
          | interface
          | bucle_mientras
          | bucle_para
          | condicional
          | garantia
          | importacion
          | usar
          | macro
          | impresion
          | retorno
          | hilo
          | llamada
          | switch
          | try_catch
          | throw_stmt
          | with_stmt
          | option
          | expr

asignacion: ("var"|"variable")? IDENTIFICADOR "=" expr
decorador: "@" IDENTIFICADOR
funcion: decorador* ("func"|"definir") IDENTIFICADOR "(" parametros? ")" ":" cuerpo "fin"
funcion_asincronica: decorador* "asincronico" "func" IDENTIFICADOR "(" parametros? ")" ":" cuerpo "fin"
clase: "clase" IDENTIFICADOR ":" cuerpo "fin"
enumeracion: ("enumeracion"|"enum") IDENTIFICADOR ":" IDENTIFICADOR ("," IDENTIFICADOR)* "fin"
interface: ("rasgo"|"interface") IDENTIFICADOR ":" metodo_abstracto* "fin"
metodo_abstracto: "func" IDENTIFICADOR "(" parametros? ")"
bucle_mientras: "mientras" expr ":" cuerpo "fin"
bucle_para: "para" IDENTIFICADOR "en" expr ":" cuerpo "fin"
condicional: "si" expr ":" cuerpo ("sino" ":" cuerpo)? "fin"
garantia: ("garantia"|"guard") expr ":" cuerpo "sino" ":" cuerpo "fin"
importacion: "import" CADENA
usar: "usar" CADENA
macro: "macro" IDENTIFICADOR "{" statement* "}"
impresion: "imprimir" "(" argumentos? ")"
retorno: "retorno" expr
hilo: "hilo" llamada
switch: ("segun"|"switch") expr ":" case+ ("sino" ":" cuerpo)? "fin"
case: ("caso"|"case") patron ("si" expr)? ":" cuerpo
patron: "_" | IDENTIFICADOR | valor | "(" patron ("," patron)* ")"
try_catch: ("try"|"intentar") ":" cuerpo ("catch"|"capturar") IDENTIFICADOR ":" cuerpo "fin"
throw_stmt: ("throw"|"lanzar") expr
with_stmt: "con" expr ("como" IDENTIFICADOR)? ":" cuerpo "fin"
option: "option" IDENTIFICADOR "=" expr
llamada: IDENTIFICADOR "(" argumentos? ")"
cuerpo: statement*
parametros: IDENTIFICADOR ("," IDENTIFICADOR)*
argumentos: expr ("," expr)*
?expr: coincidencia
     | valor (operador valor)*
?valor: CADENA
      | ENTERO
      | FLOTANTE
      | IDENTIFICADOR
      | llamada
      | holobit
      | lambda
      | "esperar" valor
      | "Some" "(" expr ")"
      | "None"
holobit: "holobit" "(" "[" [expr ("," expr)*] "]" ")"
lambda: "lambda" parametros? ":" expr
operador: "+"|"-"|"*"|"/"|">="|"<="|">"|"<"|"=="|"!="|"&&"|"||"

CADENA: /"[^"\n]*"|'[^'\n]*'/
ENTERO: /[0-9]+/
FLOTANTE: /[0-9]+\.[0-9]+/
IDENTIFICADOR: /[^\W\d][\w]*/

%ignore /\s+/
coincidencia: ("coincidir"|"match") expr ":" brazo_coincidencia+ ("sino" "=>" expr)? "fin"
brazo_coincidencia: "cuando" patron ("si" expr)? "=>" expr
