"""Colección de utilidades estándar para Cobra."""

from corelibs.texto import (
    mayusculas,
    minusculas,
    capitalizar,
    titulo,
    invertir,
    concatenar,
    quitar_espacios,
    dividir,
    unir,
    reemplazar,
    empieza_con,
    termina_con,
    incluye,
    rellenar_izquierda,
    rellenar_derecha,
    normalizar_unicode,
)
from corelibs.numero import (
    absoluto,
    aleatorio,
    clamp,
    desviacion_estandar,
    es_par,
    es_primo,
    factorial,
    mediana,
    moda,
    piso,
    potencia,
    promedio,
    raiz,
    redondear,
    techo,
)
from corelibs.archivo import leer, escribir, existe, eliminar
from corelibs.tiempo import ahora, formatear, dormir
from corelibs.coleccion import (
    ordenar,
    maximo,
    minimo,
    sin_duplicados,
    mapear,
    filtrar,
    reducir,
    encontrar,
    aplanar,
    agrupar_por,
    particionar,
    mezclar,
    zip_listas,
    tomar,
)
from corelibs.seguridad import hash_sha256, generar_uuid
from corelibs.red import obtener_url, enviar_post
from corelibs.sistema import obtener_os, ejecutar, obtener_env, listar_dir

__all__ = [
    "mayusculas",
    "minusculas",
    "capitalizar",
    "titulo",
    "invertir",
    "concatenar",
    "quitar_espacios",
    "dividir",
    "unir",
    "reemplazar",
    "empieza_con",
    "termina_con",
    "incluye",
    "rellenar_izquierda",
    "rellenar_derecha",
    "normalizar_unicode",
    "absoluto",
    "aleatorio",
    "clamp",
    "desviacion_estandar",
    "es_par",
    "es_primo",
    "factorial",
    "mediana",
    "moda",
    "piso",
    "potencia",
    "promedio",
    "raiz",
    "redondear",
    "techo",
    "leer",
    "escribir",
    "existe",
    "eliminar",
    "ahora",
    "formatear",
    "dormir",
    "ordenar",
    "maximo",
    "minimo",
    "sin_duplicados",
    "mapear",
    "filtrar",
    "reducir",
    "encontrar",
    "aplanar",
    "agrupar_por",
    "particionar",
    "mezclar",
    "zip_listas",
    "tomar",
    "hash_sha256",
    "generar_uuid",
    "obtener_url",
    "enviar_post",
    "obtener_os",
    "ejecutar",
    "obtener_env",
    "listar_dir",
]
