name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc g++ golang-go ruby-full rustc default-jdk clang llvm
      - name: Install system packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc go ruby rust openjdk llvm
      - name: Install system packages (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y mingw golang ruby rust jdk llvm
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "sphinx sphinx-rtd-theme pytest-cov codecov pyright"
      - name: Seguridad de dependencias
        run: |
          pip install safety
          safety check --full-report
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        if: runner.os != 'Windows'
        run: make lint
      - name: Run linters (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: make.bat lint
      - name: Run type checks
        if: runner.os != 'Windows'
        run: make typecheck  # Ejecuta mypy y pyright
      - name: Run type checks (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: make.bat typecheck  # Ejecuta mypy y pyright
      - name: Validate changelog
        run: python scripts/check_changelog.py
      - name: Run tests
        run: |
          if [ -d tests ]; then
            pytest tests src/tests --cov=src --cov-report=xml \
              --cov-report=term-missing --cov-fail-under=95
          else
            pytest src/tests --cov=src --cov-report=xml \
              --cov-report=term-missing --cov-fail-under=95
          fi
      - name: Run LLVM examples
        run: |
          PYTHONPATH=src python scripts/test_llvm_examples.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
      - name: Build docs
        run: sphinx-build -b html frontend/docs frontend/build/html
      - name: Check doc links
        run: sphinx-build -b linkcheck frontend/docs frontend/build/linkcheck

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ golang-go ruby-full rustc default-jdk
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "sphinx sphinx-rtd-theme pytest-cov codecov pyright"
      - name: Compare benchmarks
        run: python scripts/benchmarks/compare_releases.py --output benchmarks_compare.json --max-regression 10
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks_compare
          path: benchmarks_compare.json
      - name: Publicar resumen
        run: |
          python - <<'PY'
          import json, os

          data = json.load(open('benchmarks_compare.json'))
          lines = [
              "### Resultados de benchmarks",
              "",
              "| Backend | Δ Tiempo (s) | Δ Memoria (kB) |",
              "| --- | --- | --- |",
          ]
          for d in data:
              dt = d["diff_time"]
              dm = d["diff_memory_kb"]
              dt_str = f"{dt:+.4f}" if dt is not None else "N/A"
              dm_str = f"{dm:+d}" if dm is not None else "N/A"
              lines.append(f"| {d['backend']} | {dt_str} | {dm_str} |")

          with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as fh:
              fh.write("\n".join(lines))
          PY
