name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme pytest-cov codecov
          pip install pyright
      - name: Run linters
        run: |
          black --check backend/src
          flake8 backend/src
          mypy backend/src
          bandit -r backend/src
          pyright --project pyrightconfig.json
      - name: Run type checks
        run: make typecheck
      - name: Run tests
        run: pytest --cov=backend/src --cov-report=xml \
          --cov-report=term-missing --cov-fail-under=80
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
      - name: Build docs
        run: sphinx-build -b html frontend/docs frontend/build/html
