name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ golang-go ruby-full
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "sphinx sphinx-rtd-theme pytest-cov codecov pyright"
      - name: Seguridad de dependencias
        run: |
          pip install safety
          safety check --full-report
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        run: make lint
      - name: Run type checks
        run: make typecheck
      - name: Run tests
        run: pytest --cov=backend/src --cov-report=xml \
          --cov-report=term-missing --cov-fail-under=95
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
      - name: Build docs
        run: sphinx-build -b html frontend/docs frontend/build/html
      - name: Check doc links
        run: sphinx-build -b linkcheck frontend/docs frontend/build/linkcheck
