name: docker

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pcobra-cli:latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # Fijado a commit para seguridad de la cadena de suministro
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: final
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: ${{ env.IMAGE_NAME }}
          push: true
      - name: Move Docker cache
        run: mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: table
          exit-code: 1
          vuln-type: 'os,library'
          ignore-unfixed: true
      - name: Smoke test
        run: docker run --rm $IMAGE_NAME --version
      - name: Check image size
        run: |
          size=$(docker image inspect $IMAGE_NAME --format '{{.Size}}')
          echo "Image size: $size bytes"
          max_size=$((50 * 1024 * 1024))
          if [ "$size" -ge "$max_size" ]; then
            echo "Image is too large" >&2
            exit 1
          fi
      - name: Save image
        run: docker save $IMAGE_NAME -o pcobra-cli.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pcobra-cli-image
          path: pcobra-cli.tar
