name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4 (08eba0b27e820071cde6df949e0beb9ba4906955)
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5 (a26af69be951a213d495a4c3e4e4022e16d87065)
        with:
          python-version: "3.11"
      - run: pip install black
      - run: black --check .
