name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "sphinx sphinx-rtd-theme"
      - name: Build docs
        run: sphinx-build -b html frontend/docs frontend/build/html
      - name: Build root docs
        run: sphinx-build -b html docs docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          publish_branch: gh-pages
