name: Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # Fijado a commit para seguridad de la cadena de suministro
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "sphinx sphinx-rtd-theme"
      - name: Install LaTeX packages
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra latexmk
      - name: Build docs
        run: sphinx-build -b html frontend/docs frontend/build/html
      - name: Build root docs
        run: sphinx-build -b html docs docs/_build
      - name: Copy frontend docs to build dir
        run: cp -r frontend/build/html docs/_build/frontend
      - name: Build LaTeX docs
        run: sphinx-build -b latex docs docs/_build/latex
      - name: Build PDF manual
        run: make -C docs/_build/latex all-pdf
      - name: Copy PDF to build dir
        run: cp docs/_build/latex/proyectocobra.pdf docs/_build/
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build
      - uses: actions/deploy-pages@v2
