---
name: Label PRs by branch
permissions:
  contents: read
  pull-requests: "write"
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@b0a1180683c9f17424de4d71c044bea4c7b9bc7c # b0a1180
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
