name: Release Binaries
permissions:
  contents: read

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "pyinstaller"
      - name: Build executable
        run: cobra empaquetar --output dist --add-data all-bytes.dat:all-bytes.dat
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: cobra-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/cobra*
