name: Release Binaries
permissions:
  contents: write

on:
  workflow_dispatch:  # Permite ejecuciones manuales desde la UI de GitHub
  push:
    tags: ['v*.*.*']

jobs:
  release-binaries:
    uses: ./.github/workflows/build-binaries.yml
    secrets: inherit
