name: tests

on:
  push:
    paths: ['**.py', 'src/tests/**', '.github/workflows/test.yml']
  pull_request:
    paths: ['**.py', 'src/tests/**', '.github/workflows/test.yml']

permissions:
  contents: read
  security-events: write

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # Fijado a commit para seguridad de la cadena de suministro
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ golang-go ruby-full rustc default-jdk
      - name: Install system packages (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install -y --no-progress mingw golang ruby rust openjdk
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        if: runner.os != 'Windows'
        shell: bash
        run: |
          make lint
          make typecheck
      - name: Run linters (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./make.bat lint
          ./make.bat typecheck
      - name: Run tests
        shell: bash
        run: |
          if [ -d tests ]; then
            pytest tests src/tests --cov=src --cov-report=xml \
              --cov-fail-under=95
          else
            pytest src/tests --cov=src --cov-report=xml \
              --cov-fail-under=95
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
