name: tests

on:
  push:
    paths: ['**.py', 'src/tests/**', '.github/workflows/test.yml']
  pull_request:
    paths: ['**.py', 'src/tests/**', '.github/workflows/test.yml']

permissions:
  contents: read
  security-events: write

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # Fijado a commit para seguridad de la cadena de suministro
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
      - name: Install system packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ golang-go ruby-full rustc default-jdk
      - name: Install system packages (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install -y --no-progress mingw golang ruby rust openjdk
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          extra: "flask requests"
      - name: Verify extra packages
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python - <<'PY'
          import flask, requests
          PY
      - name: Verify extra packages (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -c "import flask, requests"
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        with:
          config-path: gitleaks.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        if: runner.os != 'Windows'
        shell: bash
        run: |
          make lint
          make typecheck
      - name: Run linters (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./make.bat lint
          ./make.bat typecheck
      - name: Run tests
        shell: bash
        run: |
          if [ -d tests ]; then
            pytest tests src/tests --cov=src --cov-report=xml \
              --cov-fail-under=95
          else
            pytest src/tests --cov=src --cov-report=xml \
              --cov-fail-under=95
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
        with:
          files: coverage.xml
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report
          path: coverage.xml
