name: tests

on:
  push:
    paths: ['**.py', 'tests/**', '.github/workflows/test.yml']
  pull_request:
    paths: ['**.py', 'tests/**', '.github/workflows/test.yml']

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ golang-go ruby-full
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        run: |
          isort --check backend/src src
          black --check backend/src src
          flake8 backend/src
          mypy backend/src
          bandit -r src backend/src
      - name: Run tests
        run: |
          pytest --cov=backend/src --cov-report=xml --cov-fail-under=95
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
