name: tests

on:
  push:
    paths: ['**.py', 'tests/**', '.github/workflows/test.yml']
  pull_request:
    paths: ['**.py', 'tests/**', '.github/workflows/test.yml']

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ golang-go ruby-full
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run linters
        run: |
          flake8 backend/src
          mypy backend/src
          bandit -r src backend/src
      - name: Run tests
        run: |
          pytest --cov=backend/src --cov-report=xml --cov-fail-under=95
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
