"""Constantes compartidas de targets soportados para la suite de tests."""

from pcobra.cobra.cli.target_policies import (
    BEST_EFFORT_RUNTIME_TARGETS,
    NO_RUNTIME_TARGETS,
    OFFICIAL_RUNTIME_TARGETS,
    OFFICIAL_TRANSPILATION_TARGETS,
    TRANSPILATION_ONLY_TARGETS,
    VERIFICATION_EXECUTABLE_TARGETS,
)
from pcobra.cobra.transpilers.targets import OFFICIAL_TARGETS, TIER1_TARGETS, TIER2_TARGETS

SUPPORTED_TARGETS = OFFICIAL_TARGETS
OFFICIAL_TRANSPILATION_TARGETS_IN_TESTS = OFFICIAL_TRANSPILATION_TARGETS
TIER1_SUPPORTED_TARGETS = TIER1_TARGETS
TIER2_SUPPORTED_TARGETS = TIER2_TARGETS
BEST_EFFORT_INTERNAL_RUNTIME_TARGETS = BEST_EFFORT_RUNTIME_TARGETS

assert SUPPORTED_TARGETS == OFFICIAL_TRANSPILATION_TARGETS_IN_TESTS == OFFICIAL_TARGETS
assert TIER1_SUPPORTED_TARGETS == TIER1_TARGETS
assert TIER2_SUPPORTED_TARGETS == TIER2_TARGETS
assert TIER1_SUPPORTED_TARGETS + TIER2_SUPPORTED_TARGETS == SUPPORTED_TARGETS
assert VERIFICATION_EXECUTABLE_TARGETS == ("python", "javascript")
assert set(OFFICIAL_RUNTIME_TARGETS).isdisjoint(BEST_EFFORT_INTERNAL_RUNTIME_TARGETS)
assert set(OFFICIAL_RUNTIME_TARGETS) | set(TRANSPILATION_ONLY_TARGETS) == set(SUPPORTED_TARGETS)
assert set(BEST_EFFORT_INTERNAL_RUNTIME_TARGETS) <= set(TRANSPILATION_ONLY_TARGETS)
assert set(NO_RUNTIME_TARGETS) == {"wasm", "asm"}
