"""Constantes compartidas de targets soportados para la suite de tests."""

from pcobra.cobra.cli.target_policies import (
    OFFICIAL_RUNTIME_TARGETS as CLI_OFFICIAL_RUNTIME_TARGETS,
    OFFICIAL_TRANSPILATION_TARGETS,
    TRANSPILATION_ONLY_TARGETS as CLI_TRANSPILATION_ONLY_TARGETS,
)
from pcobra.cobra.transpilers.targets import OFFICIAL_TARGETS, TIER1_TARGETS, TIER2_TARGETS

SUPPORTED_TARGETS = tuple(OFFICIAL_TARGETS)
OFFICIAL_TRANSPILATION_TARGETS_IN_TESTS = tuple(OFFICIAL_TRANSPILATION_TARGETS)
TIER1_SUPPORTED_TARGETS = tuple(TIER1_TARGETS)
TIER2_SUPPORTED_TARGETS = tuple(TIER2_TARGETS)
OFFICIAL_RUNTIME_TARGETS = CLI_OFFICIAL_RUNTIME_TARGETS
TRANSPILATION_ONLY_TARGETS = CLI_TRANSPILATION_ONLY_TARGETS

# Cobertura conservada solo como best-effort/manual; no forma parte del contrato
# oficial de runtime.
EXPERIMENTAL_RUNTIME_TARGETS = ("go", "java")
BEST_EFFORT_RUNTIME_TARGETS = EXPERIMENTAL_RUNTIME_TARGETS
NO_RUNTIME_TARGETS = tuple(
    target for target in TRANSPILATION_ONLY_TARGETS if target not in EXPERIMENTAL_RUNTIME_TARGETS
)

assert SUPPORTED_TARGETS == OFFICIAL_TRANSPILATION_TARGETS_IN_TESTS == OFFICIAL_TARGETS
assert TIER1_SUPPORTED_TARGETS == TIER1_TARGETS
assert TIER2_SUPPORTED_TARGETS == TIER2_TARGETS
assert TIER1_SUPPORTED_TARGETS + TIER2_SUPPORTED_TARGETS == SUPPORTED_TARGETS
assert set(OFFICIAL_RUNTIME_TARGETS).isdisjoint(EXPERIMENTAL_RUNTIME_TARGETS)
assert set(OFFICIAL_RUNTIME_TARGETS) | set(TRANSPILATION_ONLY_TARGETS) == set(SUPPORTED_TARGETS)
assert set(EXPERIMENTAL_RUNTIME_TARGETS) <= set(TRANSPILATION_ONLY_TARGETS)
assert set(NO_RUNTIME_TARGETS) == {"wasm", "asm"}
